#server.port=1010
spring.application.name=veebipood-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/veebipood
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

smartpost.api.base-url=${SMARTPOST_BASE_URL}
smartpost.api.key=${SMARTPOST_API_KEY}
smartpost.api.gateway-secret=${SMARTPOST_GATEWAY_SECRET}

everypay.api.base-url=https://igw-demo.every-pay.com/api
#everypay.api.base-url=https://pay.every-pay.eu/api
everypay.api.username=${EVERYPAY_API_USERNAME}
everypay.api.password=${EVERYPAY_API_PASSWORD}
everypay.api.account-name=EUR3D1
everypay.customer-url=https://err.ee

resend.api.key=${RESEND_API_KEY}
resend.email.from=onboarding@resend.dev
resend.email.to=vahermihkel@gmail.com
resend.email.subject=Hello World
resend.email.html=<p>Congrats on sending your <strong>first email</strong>!</p>
